version: '3'

networks:
  basic:

services:
  neo:
    image: neo4j:latest
    ports:
      # - 7474:7474
      # - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_http_advertised__address="localhost:7474"
      - NEO4J_dbms_connector_bolt_advertised__address="localhost:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins

  postgres:
    hostname: postgres
    container_name: postgres_deputy
    restart: always
    image:  postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=depchallenge
      - POSTGRES_INITDB_ARGS="--locale=en_US.UTF-8"
    ports:
      - 5433:5432
    volumes:
      - ./test/dockerenv/dbsetup/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./internal/data/migrations/:/migrations
    networks:
      - basic