version: '3'

networks:
  basic:

services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_logs_debug_level: DEBUG

  neo:
    image: neo4j:latest
    network_mode: bridge
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import

  postgres:
    hostname: postgres
    container_name: postgres_deputy
    restart: always
    image:  postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=depchallenge
      - POSTGRES_INITDB_ARGS="--locale=en_US.UTF-8"
    ports:
      - 5433:5432
    volumes:
      - ./test/dockerenv/dbsetup/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./internal/data/migrations/:/migrations
    networks:
      - basic