version: '3'

networks:
  basic:

services:
  neo4j:
    container_name: neo4j-lab
    image: neo4j:latest
    environment:
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_dbms_memory_heap_initialSize=512M
      - NEO4J_AUTH=neo4j/changeme
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data
      - neo4j_conf:/conf
      - ./import:/import
  volumes:
    neo4j_data:
    neo4j_conf:

  postgres:
    hostname: postgres
    container_name: postgres_deputy
    restart: always
    image:  postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=depchallenge
      - POSTGRES_INITDB_ARGS="--locale=en_US.UTF-8"
    ports:
      - 5433:5432
    volumes:
      - ./test/dockerenv/dbsetup/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./internal/data/migrations/:/migrations
    networks:
      - basic